name: complete_workflow
on: [workflow_dispatch]
jobs:
  install_localstack:
    runs-on: ubuntu-latest
    steps: 
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - 
        name: Setup Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.10'
