name: complete_workflow
on: [workflow_dispatch]
jobs:
  install_localstack:
    runs-on: ubuntu-latest
    steps: 
      - 
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - 
        name: Setup Python
        uses: actions/setup-python@v4
        with: 
          python-version: '3.10'
      - 
        name: Install Localstack
        run: |
          chmod 755 scripts/install_localstack.sh
          scripts/install_localstack.sh
      - 
        name: Zip functions
        run: |
          chmod 755 scripts/zip_functions.sh
          scripts/zip_functions.sh
      -
        name: Create roles
        run: |
          chmod 755 scripts/create_roles.sh
          scripts/create_roles.sh
      -
        name: Create resources
        run: |
          chmod 755 scripts/create_resources.sh
          scripts/create_resources.sh
      -
        name: Create functions
        run: |
          chmod 755 scripts/create_functions.sh
          scripts/create_functions.sh
      - 
        name: Create API
        run: |
          chmod 755 scripts/create_api.sh
          scripts/create_api.sh
          ::set-env name=apiID::$apiID
      -
        name: Test app
        run: |
          chmod 755 scripts/test.sh
          scripts/test.sh

          
