name: integration
on: [workflow_dispatch]
jobs:
  install_localstack:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/setup-python@v4
        with: 
          python-version: '3.10'
      - run: |
          python3 -m pip install localstack
          python3 -m pip install awscli-local[ver1]
          localstack start -d
      - run: |
          cd ..
          ls
          awslocal iam create-role --role-name lambdas --assume-role-policy-document file://roles.json
          awslocal iam create-role --role-name state-machines --assume-role-policy-document file://state_machine.json
          awslocal iam create-role --role-name apiRole --assume-role-policy-document file://api_role.json
