name: test
on: [workflow_dispatch]
jobs: 
  testAPI:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with: 
          python-version: '3.10'
      - run: |
          python3 -m pip install localstack
          python3 -m pip install awscli-local[ver1]
          localstack start -d
          awslocal apigateway create-rest-api --name 'Demo'
          awslocal apigateway get-rest-apis
          apiID=$(awslocal apigateway get-rest-apis | jq -r '.items[] | select(.name="local-localstack-demo") | .id')
          echo $apiID
          parentID=$(awslocal apigateway get-resources --rest-api-id $apiID | jq -r '.items[] | .id')
          resourceID=$(awslocal apigateway create-resource --rest-api-id $apiID --parent-id $parentID --path-part requests | jq -r '.id')
          awslocal apigateway put-method --rest-api-id $apiID --resource-id $resourceID --http-method POST --authorization-type "NONE"
